Better support for using the IRQ line in I2C
adafruit/Adafruit-PN532 pull request #82
Opened 2020-09-24 20:59 UTC by Udinic

Using the IRQ line we can save the host controller from being blocked waiting for new cards. When a new card is detected, the PN532 will drive the IRQ to be low (It's usually high, see [the PN532 user manual](https://www.nxp.com/docs/en/user-guide/141520.pdf)), which will let the host controller know it can try to read the detected card. This frees the host controller to do other things while waiting for new cards to be detected.

To implement this, I added a method for starting the card detection mode (startPassiveTargetIDDetection()) and another method for reading the detected card (readDetectedPassiveTargetID()). We need the PN532 to be connected using I2C and have the IRQ line connected to one of the pins in the host controller. The flow is like this:
1. Host controller calls startPassiveTargetIDDetection()
2. Assuming the IRQ is connected to pin D2, when this pin is low then we know there's a card detected by the reader.
3. The host controller calls readDetectedPassiveTargetID() to read the card information.
4. Host controller can call startPassiveTargetIDDetection() again to start listening again for new cards.

I added readMifareClassicIrq.ino as a working example for this method. There's more documentation in the example, including a wiring diagram.

This code was tested with both Arduino Mega2560 and ESP32. The changes I made are adding a new functionality and aren't affecting any existing functionality. Everything is backward compatible. The new feature is only relevant in I2C mode, SPI or UART modes aren't affected.

I added this code because there's no clear example how to use the IRQ line, not in the [official tutorial](https://learn.adafruit.com/adafruit-pn532-rfid-nfc/breakout-wiring) nor in any of the relevant discussion forums. I hope this helps others like me who struggled trying to get this behavior to work.

2020-10-31 00:15 UTC, siddacious requested changes
@Udinic It looks like the `clang-format` check is failing; please take a look at the info in the README to get it passing. Thanks :)

https://github.com/adafruit/Adafruit-PN532#formatting-and-clang-format

2020-11-01 20:59 UTC, Udinic commented
Rebased + formatted the code using clang-format

2020-11-23 18:43 UTC, siddacious approved these changes

2020-11-23 18:43 UTC, siddacious commented
I'm going to go ahead and merge since the doxygen failures are for pre-existing code

2020-11-23 18:43 UTC, merged